"""
Neo4j graph store types and models.

Defines the data structures for temporal knowledge graph storage.
"""

from typing import Optional, List, Dict, Any
from datetime import datetime
from dataclasses import dataclass, field
from enum import Enum


class NodeType(str, Enum):
    """
    Types of nodes in the knowledge graph.
    
    ENTITY: A specific entity (person, technology, tool, etc.)
    CONCEPT: An abstract concept or idea
    EVENT: A temporal event or occurrence
    DECISION: A decision made by the user
    """
    ENTITY = "Entity"
    CONCEPT = "Concept"
    EVENT = "Event"
    DECISION = "Decision"


class RelationType(str, Enum):
    """
    Common relationship types in the knowledge graph.

    The graph now supports dynamic/semantic relationship labels generated
    by the LLM (e.g. "lives_in", "prefers", "works_at").  These enum
    values are kept as canonical fallbacks and for backward compatibility.
    """
    USES = "USES"
    RELATES_TO = "RELATES_TO"
    CAUSED_BY = "CAUSED_BY"
    REPLACED_BY = "REPLACED_BY"
    INTERACTS_WITH = "INTERACTS_WITH"
    # Dynamic labels from LLM extraction are stored as raw strings
    # on the relationship and written to Neo4j directly.  See
    # graph_store.add_relationship_dynamic().


@dataclass
class GraphNode:
    """
    A node in the knowledge graph.
    
    Attributes:
        id: Optional unique identifier (generated by Neo4j if not provided)
        label: Node label (Entity, Concept, etc.)
        name: Entity name/text
        node_type: Type of entity (technology, person, etc.)
        properties: Additional properties
        created_at: Creation timestamp
        last_seen: Last time this entity was mentioned
    """
    label: NodeType
    name: str
    node_type: str = ""
    properties: Dict[str, Any] = field(default_factory=dict)
    id: Optional[str] = None
    created_at: datetime = field(default_factory=datetime.utcnow)
    last_seen: datetime = field(default_factory=datetime.utcnow)


@dataclass
class GraphRelationship:
    """
    A relationship between two nodes in the knowledge graph.
    
    Attributes:
        from_node: Source node name
        to_node: Target node name
        rel_type: Type of relationship
        properties: Additional properties
        confidence: Confidence score (0.0-1.0)
        created_at: Creation timestamp
        source_conversation_id: Conversation where this was extracted
    """
    from_node: str
    to_node: str
    rel_type: RelationType
    properties: Dict[str, Any] = field(default_factory=dict)
    confidence: float = 0.8
    created_at: datetime = field(default_factory=datetime.utcnow)
    source_conversation_id: Optional[str] = None
